Repository ita-social-projects/Home-UI, pull requests merged in 2021-09, with the labels that each got.

#17 #14 - make axios global HTTP instance
  src/core/api/http-common.ts
  src/main.ts
  src/shims-vue.d.ts
Labels: feature, UI

#25 Feature/uikit
  package-lock.json
  package.json
  src/styles/index.scss
Labels: feature, UI

#27 Feature/16/vuex strict
  src/shims-vuex.d.ts
  src/store/index.ts
Labels: feature, UI

#28 ui/prettier-config
  prettier.config.js
Labels: UI

#32 Features/12/git hooks
  .eslintcache
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  src/App.vue
  src/main.ts
  src/views/__tests__/Home.spec.ts
Labels: feature, UI

#35 ui/34/eslintcache
  .eslintcache
  .gitignore
  package-lock.json
  package.json
Labels: UI

#42 #41 config: axios instance
  src/core/api/http-common.ts
Labels: bug, UI

#43 #19 add Header, logo and start page
  src/App.vue
  src/assets/logo.png
  src/assets/logo.svg
  src/components/base/BaseHeader.vue
  src/router/index.ts
  src/views/Home.vue
  src/views/StartPage.vue
  src/views/UserLogin.vue
Labels: feature, UI

#45 Feature 23/login system
  package-lock.json
  package.json
  src/views/Home.vue
  src/views/UserLogin.vue
  src/views/__tests__/UserLogin.spec.ts
Labels: feature, UI

#44 Feature 21/coop registration
  .eslintrc.js
  package-lock.json
  src/main.ts
  src/router/index.ts
  src/store/cooperationModule.ts
  src/store/index.ts
  src/styles/_fonts.scss
  src/styles/index.scss
  src/styles/style.scss
  src/styles/variables.scss
  src/utils/validators.ts
  src/views/RegisterCooperation.vue
  src/views/UserLogin.vue
Labels: feature, UI

#49 #48 - adjusted jest config
  jest.config.js
Labels: bug

#53 #52 Toast notifications
  public/favicon.ico
  src/App.vue
  src/main.ts
Labels: feature, UI

#55 Task 43/routes config
  src/components/base/BaseHeader.vue
  src/router/index.ts
  src/router/types.ts
  src/views/StartPage.vue
  src/views/UserLogin.vue
Labels: UI, dev only

#56 #54 vuex & cooperation module
  src/shims-vuex.d.ts
  src/store/cooperation/actions.ts
  src/store/cooperation/getters.ts
  src/store/cooperation/index.ts
  src/store/cooperation/mutations.ts
  src/store/cooperation/types.ts
  src/store/cooperationModule.ts
  src/store/index.ts
  src/store/types.ts
Labels: feature, UI, dev only

#58 Feature 23/login system
  src/styles/style.scss
  src/utils/validators.ts
  src/views/UserLogin.vue
  src/views/__tests__/UserLogin.spec.ts
Labels: feature, UI

#46 Feature 21/coop registration
  package-lock.json
  src/main.ts
  src/styles/_variables.scss
  src/styles/index.scss
  src/styles/variables.scss
  src/views/RegisterCooperation.vue
  src/views/__tests__/RegisterCooperation.spec.ts
Labels: feature, UI

#64 Edit store configuration
  src/shims-vuex.d.ts
  src/store/cooperation/actions.ts
  src/store/cooperation/getters.ts
  src/store/cooperation/index.ts
  src/store/cooperation/mutations.ts
  src/store/cooperation/types.ts
  src/store/index.ts
  src/store/types.ts
  src/styles/style.scss
Labels: dev only

#87 Feature 24/main skeleton
  src/App.vue
  src/components/base/BaseHeader.vue
  src/components/base/Sidebar.vue
  src/router/index.ts
  src/router/types.ts
  src/styles/style.scss
  src/views/CooperationInfo.vue
  src/views/Home.vue
  src/views/MainPage.vue
  src/views/StartPage.vue
  src/views/__tests__/Home.spec.ts
Labels: User Story, UI

#85 Feature 57/vuex modules sign in
  src/components/base/BaseHeader.vue
  src/components/base/Sidebar.vue
  src/router/index.ts
  src/store/authorization/actions.ts
  src/store/authorization/getters.ts
  src/store/authorization/index.ts
  src/store/authorization/mutations.ts
  src/store/authorization/types.ts
  src/store/index.ts
  src/views/Home.vue
  src/views/MainPage.vue
  src/views/RegisterCooperation.vue
  src/views/UserLogin.vue
  src/views/__tests__/Home.spec.ts
Labels: UI, Dev Only
