Repository ita-social-projects/Home-UI, pull requests merged in 2021-10, with the labels that each got.

#91 Feature 24/main skeleton
  src/App.vue
  src/components/Header.vue
  src/components/PageNotFound.vue
  src/components/Sidebar.vue
  src/components/base/BaseSidebarNavButton.vue
  src/router/index.ts
  src/router/types.ts
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/index.scss
  src/styles/style.scss
  src/views/MainPage.vue
  src/views/RegisterCooperation.vue
  src/views/RegisterUser.vue
  src/views/StartPage.vue
  src/views/UserLogin.vue
Labels: User Story, UI

#101 #92 Added Vuex localstorage module
  src/store/authorization/actions.ts
  src/store/authorization/mutations.ts
  src/store/authorization/types.ts
  src/store/index.ts
  src/store/localstorage/actions.ts
  src/store/localstorage/getters.ts
  src/store/localstorage/index.ts
  src/store/localstorage/mutations.ts
  src/store/localstorage/types.ts
  src/store/types.ts
Labels: UI, Dev Only

#102 Vuex Store core changes
  src/shims-vuex.d.ts
  src/store/authorization/actions.ts
  src/store/authorization/getters.ts
  src/store/authorization/mutations.ts
  src/store/authorization/types.ts
  src/store/cooperation/actions.ts
  src/store/cooperation/getters.ts
  src/store/cooperation/index.ts
  src/store/cooperation/mutations.ts
  src/store/cooperation/types.ts
  src/store/index.ts
  src/store/localstorage/mutations.ts
  src/store/localstorage/types.ts
  src/store/types.ts
  src/views/CooperationInfo.vue
  src/views/MainPage.vue
  src/views/UserLogin.vue
Labels: UI, Dev Only

#106 #23 Sign in
  src/core/api/http-common.ts
  src/core/interceptors/index.ts
  src/router/index.ts
  src/store/authorization/actions.ts
  src/views/UserLogin.vue
Labels: User Story, UI, Tech Debt

#107 Feature 40/manage coop info
  src/store/cooperation/actions.ts
  src/store/cooperation/getters.ts
  src/store/cooperation/index.ts
  src/store/cooperation/mutations.ts
  src/store/cooperation/types.ts
  src/views/CooperationInfo.vue
Labels: User Story, UI, Tech Debt
