Repository ita-social-projects/Home-UI, pull requests merged in 2022-02, with the labels that each got.

#322 Tech debt/ extracting list of houses
  src/components/ListOfHouses.vue
  src/views/CooperationInfo.vue
Labels: UI, Tech Debt

#310 Feature 88/create poll
  src/components/CreatePollForm.vue
  src/components/EditCooperationPollForm.vue
  src/store/polls/actions.ts
  src/store/polls/mutations.ts
  src/store/polls/types.ts
  src/utils/poll-validations.ts
  src/utils/validators.ts
  src/views/CooperationPolls.vue
Labels: User Story, UI, Tech Debt

#309 Feature 140/apartment section
  src/components/AddApartmentForm.vue
  src/components/EditApartmentForm.vue
  src/components/__tests__/EditApartmentForm.spec.ts
  src/shared/models/contactsDTO.modal.ts
  src/shared/models/owner.model.ts
  src/shared/models/ownerDTO.model.ts
  src/shared/models/ownerships.model.ts
  src/shared/models/ownershipsDTO.model.ts
  src/shared/models/update-ownershipsDTO.model.ts
  src/store/apartments/actions.ts
  src/store/apartments/getters.ts
  src/store/apartments/index.ts
  src/store/apartments/models/add-apartment.model.ts
  src/store/apartments/models/apartment.model.ts
  src/store/apartments/models/apartmentDTO.model.ts
  src/store/apartments/models/update-upartmentDTO.model.ts
  src/store/apartments/mutations.ts
  src/store/apartments/types.ts
  src/store/authorization/types.ts
  src/store/index.ts
  src/store/models/post-contact.model.ts
  src/store/ownerships/actions.ts
  src/store/ownerships/getters.ts
  src/store/ownerships/index.ts
  src/store/ownerships/mutations.ts
  src/store/ownerships/types.ts
  src/store/types.ts
  src/store/user/types.ts
  src/utils/apartment-validations.ts
  src/utils/test-utils.ts
  src/utils/validators.ts
  src/views/ApartmentInfo.vue
  src/views/ManageApartments.vue
  src/views/RegisterUser.vue
Labels: User Story, UI, Tech Debt

#337 Tech debt/apartment packaging
  src/apartment/ApartmentForm.vue
  src/apartment/ApartmentInfo.vue
  src/apartment/ManageApartments.vue
  src/apartment/models/add-apartmentDTO.model.ts
  src/apartment/models/apartment.model.ts
  src/apartment/models/apartmentDTO.model.ts
  src/apartment/models/owner.model.ts
  src/apartment/models/ownerDTO.model.ts
  src/apartment/models/ownerships.model.ts
  src/apartment/models/ownershipsDTO.model.ts
  src/apartment/models/update-ownershipsDTO.model.ts
  src/apartment/models/update-upartmentDTO.model.ts
  src/apartment/store/apartments/actions.ts
  src/apartment/store/apartments/getters.ts
  src/apartment/store/apartments/index.ts
  src/apartment/store/apartments/mutations.ts
  src/apartment/store/apartments/types.ts
  src/apartment/store/ownerships/actions.ts
  src/apartment/store/ownerships/getters.ts
  src/apartment/store/ownerships/index.ts
  src/apartment/store/ownerships/mutations.ts
  src/apartment/store/ownerships/types.ts
  src/apartment/validation/apartment-validations.ts
  src/components/CreateInvitationForm.vue
  src/router/index.ts
  src/store/index.ts
  src/store/types.ts
  src/views/__tests__/ManageApartments.spec.ts
Labels: UI, Tech Debt

#334 packaging cooperation management
  src/apartment/ApartmentInfo.vue
  src/apartment/ManageApartments.vue
  src/components/CreateInvitationForm.vue
  src/components/EditCooperationPollForm.vue
  src/components/__tests__/EditCooperationForm.spec.ts
  src/components/base/BaseCooperationPoll.vue
  src/cooperation/components/CooperationInfo.vue
  src/cooperation/components/EditCooperationForm.vue
  src/cooperation/components/RegisterCooperation.vue
  src/cooperation/models/cooperation.model.ts
  src/cooperation/models/cooperationDTO.model.ts
  src/cooperation/models/put-cooperationDTO.model.ts
  src/cooperation/store/actions.ts
  src/cooperation/store/getters.ts
  src/cooperation/store/index.ts
  src/cooperation/store/mutations.ts
  src/cooperation/store/types.ts
  src/cooperation/utils/validators/cooperation-validations.ts
  src/router/index.ts
  src/store/index.ts
  src/store/types.ts
  src/views/CooperationPolls.vue
  src/views/__tests__/CooperationInfo.spec.ts
  src/views/__tests__/RegisterCooperation.spec.ts
Labels: Tech Debt

#338 Tech-debt: correct types for house mnmgnt and refactoring
  src/apartment/ApartmentInfo.vue
  src/apartment/ManageApartments.vue
  src/apartment/store/apartments/getters.ts
  src/apartment/store/apartments/types.ts
  src/components/CreateInvitationForm.vue
  src/houses/components/ListOfHouses.vue
  src/houses/components/ManageHouseForm.vue
  src/houses/components/ManageHouses.vue
  src/houses/models/houseDTO.model.ts
  src/houses/store/actions.ts
  src/houses/store/getters.ts
  src/houses/store/mutations.ts
  src/houses/store/types.ts
  src/store/polls/models/put-pollDTO.model.ts
  src/store/polls/types.ts
  src/views/__tests__/ManageApartments.spec.ts
Labels: UI, Tech Debt
