Repository ita-social-projects/Home-UI, pull requests merged in 2022-01, with the labels that each got.

#267 Merge Manage apartments/unit tests into develop
  src/components/AddApartmentForm.vue
  src/components/AddHouseForm.vue
  src/components/DetailedInfo.vue
  src/components/EditCooperationInfo.vue
  src/components/EditHouseForm.vue
  src/components/__tests__/AddApartmentForm.spec.ts
  src/components/__tests__/AddHouseForm.spec.ts
  src/components/__tests__/EditCooperationForm.spec.ts
  src/store/houses/actions.ts
  src/utils/house-validations.ts
  src/utils/test-utils.ts
  src/utils/validators.ts
  src/views/ManageApartments.vue
  src/views/__tests__/CooperationInfo.spec.ts
  src/views/__tests__/ManageApartments.spec.ts
  src/views/__tests__/ManageUser.spec.ts
  src/views/__tests__/RegisterCooperation.spec.ts
Labels: Dev Only

#269 btns are disabled until user corrects some fields
  src/components/EditCooperationInfo.vue
  src/components/EditHouseForm.vue
  src/components/__tests__/EditCooperationForm.spec.ts
  src/utils/validators.ts
  src/views/ManageApartments.vue
Labels: Tech Debt

#271 Tech debt/routing to cooperation
  src/views/MainPage.vue
Labels: Tech Debt

#272 Manage apartments/unit tests
  src/views/__tests__/ManageApartments.spec.ts
Labels: Dev Only

#277 Feature 122/create invitation
  src/components/CreateInvitationForm.vue
  src/store/apartments/getters.ts
  src/store/apartments/types.ts
  src/store/houses/getters.ts
  src/store/houses/types.ts
  src/store/invitations/actions.ts
  src/store/invitations/models/invitationApart.model.ts
  src/store/invitations/models/invitationApartDTO.model.ts
  src/store/invitations/models/post-invitation.DTOmodel.ts
  src/store/invitations/models/post-invitation.model.ts
  src/store/invitations/mutations.ts
  src/store/invitations/types.ts
  src/store/types.ts
  src/views/InvitationSection.vue
  src/views/MainPage.vue
Labels: User Story

#308 Feature 122/create invitation
  src/components/CreateInvitationForm.vue
  src/store/invitations/actions.ts
  src/store/invitations/models/invitation.model.ts
  src/store/invitations/models/invitationDTO.model.ts
  src/store/invitations/models/post-invitation.model.ts
  src/store/invitations/mutations.ts
  src/store/invitations/types.ts
  src/views/InvitationSection.vue
Labels: UI, Epic

#315 fixed contact-type-enum
  src/store/authorization/types.ts
Labels: Bug

#311 Feature 279/update poll
  src/components/CreateInvitationForm.vue
  src/components/EditCooperationPollForm.vue
  src/components/base/BaseCooperationPoll.vue
  src/store/authorization/types.ts
  src/store/models/post-contact.model.ts
  src/store/polls/actions.ts
  src/store/polls/index.ts
  src/store/polls/models/poll.model.ts
  src/store/polls/models/pollDTO.model.ts
  src/store/polls/models/put-pollDTO.model.ts
  src/store/polls/mutations.ts
  src/store/polls/types.ts
  src/utils/validators.ts
  src/views/ManageUser.vue
  src/views/PollInfo.vue
Labels: UI, Epic
